### PR TITLE
fix: handle missing user fields and token expiry

### LINKED ISSUE #31: arl invalid or expired error
### Bug Description

Cannot launch the app neither with the email/password set in secrets, nor the arl. "arl invalid or expired" error is shown in both cases. The same arl works fine when using Deezer through Lyrion Media Server plugin on the same machine.

### Steps to Reproduce

1. Launch the app with "pleezer -s".
2. Observe error message.

### Logs

```shell
denys@raspberrypi:~ $ pleezer --name "BasX" -s /home/denys/secrets.toml -vv
[2024-11-25T12:57:57Z DEBUG pleezer] Command Args {
        secrets_file: "/home/denys/secrets.toml",
        name: Some(
            "BasX",
        ),
        device: None,
        no_interruptions: false,
        hook: None,
        quiet: false,
        verbose: 2,
        eavesdrop: false,
    }
[2024-11-25T12:57:57Z INFO  pleezer] starting pleezer/0.2.0; release; en
[2024-11-25T12:57:57Z INFO  pleezer] using arl from secrets file
[2024-11-25T12:57:57Z TRACE pleezer] device uuid: 02b65b79-f09d-5686-ae9a-e26874337ba2
[2024-11-25T12:57:57Z TRACE pleezer] user agent: pleezer/0.2.0 (Rust; linux/12; like Desktop; en)
[2024-11-25T12:57:57Z TRACE pleezer] client id: 473013585
[2024-11-25T12:57:57Z DEBUG pleezer::player] no bf_secret specified, fetching one from the web player
[2024-11-25T12:57:58Z TRACE pleezer::config] bootstrapping from https://e-cdn-files.dzcdn.net/cache/js/app-web.c10e656b5b37510df88f.js
[2024-11-25T12:57:58Z INFO  pleezer::player] audio output device: default on ALSA
[2024-11-25T12:57:58Z TRACE pleezer::remote] remote version: 2000
[2024-11-25T12:57:58Z ERROR pleezer] Permission denied { arl invalid or expired }
```

### Operating System

Raspberry Pi OS 12

### pleezer version

0.2.0

### Rust version (if building from source)

1.82.0

### Hardware specifications

Raspberry Pi 5 4GB

### Deezer client specifications

10.25.1.1 - iOS 18.1.1

### Additional Context

_No response_

### Due Diligence

- [X] I am using the [latest version](https://github.com/roderickvd/pleezer/releases) of pleezer
- [X] I have searched the [issues](https://github.com/roderickvd/pleezer/issues) for similar reports
- [X] I have included a full verbose log from launch to the issue, not just an excerpt
- [X] I confirm that this is an issue with pleezer, not with my system configuration or other software
- [X] I confirm that this is not a security issue, which should be [reported](https://github.com/roderickvd/pleezer/security/policy) privately
- [X] I have read and understood the [Contributing guidelines](https://github.com/roderickvd/pleezer/blob/main/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by roderickvd**
## Description

Fixes two user-related issues in the gateway:
- Allow partial user data parsing with default values
- Correct the user token expiration logic

## Related Issues

Fixes #31

## Implementation Details

Changes the `UserData` deserialisation to rely on defaults where possible.

## Testing

Tested locally, but needs user feedback from #31.

## Due Diligence

Please confirm that you have completed the following tasks by checking the boxes:

- [x] I have linked any related [issues or feature requests](https://github.com/roderickvd/pleezer/issues).
- [x] I have selected the appropriate labels for this pull request.
- [x] I have performed cross-platform testing if possible.
- [x] I have updated the [CHANGELOG.md](https://github.com/roderickvd/pleezer/blob/main/CHANGELOG.md) file with a summary of my changes under the "Unreleased" section.
- [x] I have kept the pull request as a draft until it is ready for review (if applicable).
- [x] I have read and understood the [Contributing guidelines](https://github.com/roderickvd/pleezer/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roderickvd** [comment]
@denys-lysiuk would you please verify?

**Comment by denys-lysiuk** [comment]
> @denys-lysiuk would you please verify?

Still no luck unfortunately. Tried with email/password and arl.

[logs.zip](https://github.com/user-attachments/files/17929994/logs.zip)

**Comment by roderickvd** [comment]
Argh 😬 I'll give it another go tonight. Good news is: you authenticate just fine, it's just that I need to fix the parsing of the response you're getting. It's different from mine.

**Comment by roderickvd** [comment]
@denys-lysiuk if you would please check again?

**Comment by denys-lysiuk** [comment]
> @denys-lysiuk if you would please check again?

It's working!

**Pull request merged**
